### ISSUE TITLE
Pugjs compliance to-do list

### ISSUE THREAD

**Issue by kylekatarnls** [phug-php/phug#2]
- [x] dynamic mixin names
- [ ] interpolation in comments
- [x] recursive mixins
- [x] recursive interpolation
- [x] empty piped text line add whitespace

**Comment by kylekatarnls** [comment]
`interpolation in comments` seems a risky change and a big effort cost for few advantage. So it will be kept as known limitation.

But if someone want to do a proposition for this alignment I'm open to discussion.
